### Crear un nuevo usuario
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "PROBANDO@GMAIL.COM",
  "name": "PROBANDO",
  "password": "123456789"
}

### Login de un usuario existente
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "test@test.test",
  "password": "123456789"
}

### Crear una nueva categoría
POST http://localhost:3000/api/categories
Content-Type: application/json

{
  "name": "Prueba",
  "userId": "6a961bcc-02b7-4f86-a793-70313636e4ff"
}


### Crear movimiento de ingreso
POST http://localhost:3000/api/movement
Content-Type: application/json

{
  "description": "Carga de prueba",
  "amount": 120000,
  "type": "expense",
  "categoryId": "a75cb2b6-90ec-4779-bd03-798fc86d1887",
  "date": "2025-06-17"
}


### Iniciar sesión
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "ariel@ariel.ariel",
    "password": "123456789"

}


### Obtener todas las categorías
GET http://localhost:3000/api/categories

### Obtener todos los gastos
GET http://localhost:3000/api/movement

###
GET http://localhost:3000/api/auth/me

