### Crear un nuevo usuario
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "PROBANDO@GMAIL.COM",
  "name": "PROBANDO",
  "password": "123456789"
}

### Login de un usuario existente
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "PROBANDO@GMAIL.COM",
  "password": "123456789"
}

### Crear una nueva categoría
POST http://localhost:3000/api/categories
Content-Type: application/json

{
  "name": "PROBANDO"
}


### Crear movimiento de ingreso
POST http://localhost:3000/api/movement
Content-Type: application/json

{
  "description": "PROBANDO",
  "amount": 555,
  "type": "income",
  "categoryId": "7c2c704d-9b4a-48db-a47a-36d9515c6377"
}


### Iniciar sesión
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "ariel@ariel.ariel",
    "password": "123456789"

}


### Obtener todas las categorías
GET http://localhost:3000/api/categories

### Obtener todos los gastos
GET http://localhost:3000/api/movement

###
GET http://localhost:3000/api/auth/me

