### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=WebStorm

###
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "id": 0,
  "email": "prueba@prueba.com",
  "name": "Prueba",
  "pass": "1234"
}

###


### login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "prueba@prueba.com",
    "pass": "1234"

}

###
GET http://localhost:3000/api/users



###
POST http://localhost:3000/api/categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjAsImlhdCI6MTc1MDExNjAwNywiZXhwIjoxNzUwNzIwODA3fQ.rVslCWEF4jUOFId_CIDs7h6BHcY7q99y1k6HOeSfaSk

{
  "name": "Supermercado"
}

###
POST http://localhost:3000/api/expenses
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjAsImlhdCI6MTc1MDExNjAwNywiZXhwIjoxNzUwNzIwODA3fQ.rVslCWEF4jUOFId_CIDs7h6BHcY7q99y1k6HOeSfaSk

{
  "amount": 100,
  "description": "Carga de sube",
  "date": "2025-02-10"
}

###
GET http://localhost:3000/api/categories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjAsImlhdCI6MTc1MDExNjAwNywiZXhwIjoxNzUwNzIwODA3fQ.rVslCWEF4jUOFId_CIDs7h6BHcY7q99y1k6HOeSfaSk

### login
POST http://localhost:3000/api/auth/login
Content-Type: application/json
