### Obtener todos los gastos del usuario logueado
GET http://localhost:3000/api/movement

### Obtener un movimiento del usuario logueado por categoría
GET http://localhost:3000/api/movement/category/03e1b6b7-47d1-4c66-9d64-858fdc02f9fc

### Obtener todos los ingresos del usuario logueado
GET http://localhost:3000/api/movement/incomes

### Obtener todos los gastos del usuario logueado
GET http://localhost:3000/api/movement/expenses

### Crear movimiento de gasto del usuario logueado
POST http://localhost:3000/api/movement
Content-Type: application/json

{
  "description": "fruteria",
  "amount": 1565,
  "type": "expense",
  "categoryId": "03e1b6b7-47d1-4c66-9d64-858fdc02f9fc"
}

### Crear movimiento de ingreso del usuario logueado
POST http://localhost:3000/api/movement
Content-Type: application/json

{
  "description": "Sueldo de junio",
  "amount": 65000,
  "type": "income",
  "categoryId": "a84626fb-f63f-42a6-9d16-734c781f6c05"
}

### Actualizar movimiento del usuario logueado
PUT http://localhost:3000/api/movement/1eb362ea-2448-4c6f-8768-19215b9f2902
Content-Type: application/json

{
  "description": "Compra de frutas",
  "amount": 9,
  "type": "expense",
  "categoryId": "03e1b6b7-47d1-4c66-9d64-858fdc02f9fc"
}

### Eliminar movimiento del usuario logueado
DELETE http://localhost:3000/api/movement/68289003-2725-405d-86db-35ea748e6901