### Obtener todos los gastos del usuario logueado
GET http://localhost:3000/api/movement

### Obtener un movimiento del usuario logueado por categoría
GET http://localhost:3000/api/movement/category/5f692ef2-d1a4-4cf2-994c-831f3c8d311b

### Obtener todos los ingresos del usuario logueado
GET http://localhost:3000/api/movement/type/income

### Obtener todos los gastos del usuario logueado
GET http://localhost:3000/api/movement/type/expense

### Crear movimiento de gasto del usuario logueado
POST http://localhost:3000/api/movement
Content-Type: application/json

{
  "description": "fruteria",
  "amount": 1565,
  "type": "expense",
  "categoryId": "5d2c6d16-df94-4e04-a045-167833a5ff69"
}

### Crear movimiento de ingreso del usuario logueado
POST http://localhost:3000/api/movement
Content-Type: application/json

{
  "description": "Sueldo de junio",
  "amount": 65000,
  "type": "income",
  "categoryId": "5f692ef2-d1a4-4cf2-994c-831f3c8d311b"
}

### Actualizar movimiento del usuario logueado
PUT http://localhost:3000/api/movement/ecb512fa-92ee-4d0b-8de4-e0e74e5f03a7
Content-Type: application/json

{
  "description": "frutas del jardin",
  "amount": 200,
  "type": "expense",
  "categoryId": "5d2c6d16-df94-4e04-a045-167833a5ff69"
}

### Eliminar movimiento del usuario logueado
DELETE http://localhost:3000/api/movement/ecb512fa-92ee-4d0b-8de4-e0e74e5f03a7